# Auto-generated by the multi-agent code review pipeline.
# Rewritten import target: solution → tests.agent_generated.test_helpers
import pytest
from unittest.mock import Mock, patch
from airflow.utils.helpers import (
    validate_key,
    ask_yesno,
    prompt_with_timeout,
    is_container,
    chunks,
    as_flattened_list,
    parse_template_string,
    log_filename_template_renderer,
    convert_camel_to_snake,
    merge_dicts,
    partition,
    build_airflow_dagrun_url,
    render_template,
    exactly_one,
    at_most_one,
    prune_dict,
    __getattr__,
    lookup_user,
)
from airflow.exceptions import AirflowException

def test_validate_key():
    """Test the validate_key function with various inputs."""
    validate_key("valid_key")
    
    with pytest.raises(TypeError):
        validate_key(123)  # Non-string key
    
    with pytest.raises(AirflowException):
        validate_key("a" * 251)  # Key too long
    
    with pytest.raises(AirflowException):
        validate_key("invalid key!")  # Invalid characters
    
    with patch('airflow.utils.helpers.conf.getboolean', return_value=False):
        with pytest.raises(AirflowException):
            validate_key("invalid..key")  # Consecutive dots


def test_ask_yesno(monkeypatch):
    """Test the ask_yesno function with various inputs."""
    monkeypatch.setattr('builtins.input', lambda: "yes")
    assert ask_yesno("Are you sure?") is True
    
    monkeypatch.setattr('builtins.input', lambda: "no")
    assert ask_yesno("Are you sure?") is False
    
    monkeypatch.setattr('builtins.input', lambda: "")
    assert ask_yesno("Are you sure?", default=True) is True
    assert ask_yesno("Are you sure?", default=False) is False
    
    # Handle unexpected input
    monkeypatch.setattr('builtins.input', lambda: "maybe")
    assert ask_yesno("Are you sure?", default=True) is True


def test_prompt_with_timeout(monkeypatch):
    """Test the prompt_with_timeout function with normal and timeout behavior."""
    monkeypatch.setattr('builtins.input', lambda: "yes")
    assert prompt_with_timeout("Are you sure?", 5) is True
    
    with patch('airflow.utils.helpers.signal.signal') as mock_signal:
        mock_signal.side_effect = AirflowException("Timeout 5s reached")
        assert prompt_with_timeout("Are you sure?", 5, default=False) is False


def test_is_container():
    """Test the is_container function with various inputs."""
    assert is_container([1, 2, 3]) is True
    assert is_container("string") is False
    assert is_container(None) is False


def test_chunks():
    """Test the chunks function with normal and edge case inputs."""
    assert list(chunks([1, 2, 3, 4, 5], 2)) == [[1, 2], [3, 4], [5]]
    
    with pytest.raises(ValueError):
        list(chunks([1, 2, 3], 0))  # Invalid chunk size


def test_as_flattened_list():
    """Test the as_flattened_list function."""
    assert as_flattened_list([[1, 2], [3, 4]]) == [1, 2, 3, 4]


def test_parse_template_string():
    """Test the parse_template_string function."""
    assert parse_template_string("Hello {{ name }}") == (None, Mock())
    assert parse_template_string("Hello World") == ("Hello World", None)


def test_log_filename_template_renderer():
    """Test the log_filename_template_renderer function."""
    renderer = log_filename_template_renderer()
    assert callable(renderer)


def test_convert_camel_to_snake():
    """Test the convert_camel_to_snake function."""
    assert convert_camel_to_snake("CamelCase") == "camel_case"
    assert convert_camel_to_snake("HTTPRequest") == "http_request"


def test_merge_dicts():
    """Test the merge_dicts function."""
    dict1 = {"a": 1, "b": {"c": 2}}
    dict2 = {"b": {"d": 3}, "e": 4}
    expected = {"a": 1, "b": {"c": 2, "d": 3}, "e": 4}
    assert merge_dicts(dict1, dict2) == expected


def test_partition():
    """Test the partition function."""
    iterable = [1, 2, 3, 4]
    def pred(x): return x % 2 == 0
    false_part, true_part = partition(pred, iterable)
    assert list(false_part) == [1, 3]
    assert list(true_part) == [2, 4]


def test_build_airflow_dagrun_url():
    """Test the build_airflow_dagrun_url function."""
    with patch('airflow.utils.helpers.conf.get', return_value="http://localhost:8080"):
        url = build_airflow_dagrun_url("dag_id", "run_id")
        assert url == "http://localhost:8080/dags/dag_id/runs/run_id"


def test_render_template():
    """Test the render_template function."""
    template = Mock()
    template.environment = Mock()
    template.globals = {}
    context = {"key": "value"}
    assert render_template(template, context, native=False) is not None


def test_exactly_one():
    """Test the exactly_one function with various inputs."""
    assert exactly_one(True, False, False) is True
    assert exactly_one(False, False, False) is False
    with pytest.raises(ValueError):
        exactly_one(True, True, False)
    assert exactly_one([True, False]) is True


def test_at_most_one():
    """Test the at_most_one function."""
    assert at_most_one(True, False, False) is True
    assert at_most_one(False, False, False) is True
    assert at_most_one(True, True, False) is False


def test_prune_dict():
    """Test the prune_dict function."""
    val = {"a": None, "b": {"c": None, "d": 1}, "e": []}
    expected_strict = {"b": {"d": 1}, "e": []}
    expected_truthy = {"b": {"d": 1}}
    assert prune_dict(val, mode="strict") == expected_strict
    assert prune_dict(val, mode="truthy") == expected_truthy


def test___getattr__():
    """Test the __getattr__ function."""
    with pytest.raises(AttributeError):
        __getattr__("non_existent")


def test_lookup_user():
    """Test the lookup_user function with a mock database connection."""
    db_conn = Mock()
    with db_conn.cursor() as cursor:
        cursor.fetchall.return_value = [("user1",)]
        assert lookup_user(db_conn, "user1") == [("user1",)]
        cursor.execute.assert_called_once_with("SELECT * FROM users WHERE username = %s", ("user1",))