# Auto-generated by the multi-agent code review pipeline.
# Rewritten import target: solution → tests.agent_generated.test_helpers
import pytest
from unittest.mock import patch, MagicMock
from tests.agent_generated.test_helpers import (
    validate_key,
    ask_yesno,
    prompt_with_timeout,
    is_container,
    chunks,
    as_flattened_list,
    parse_template_string,
    log_filename_template_renderer,
    convert_camel_to_snake,
    merge_dicts,
    partition,
    build_airflow_dagrun_url,
    render_template,
    exactly_one,
    at_most_one,
    prune_dict,
    __getattr__,
    compute_expression,
    AirflowException
)

def test_validate_key():
    """Test the validate_key function with various inputs."""
    validate_key("valid_key")
    validate_key("valid.key")
    validate_key("valid-key")
    validate_key("valid_key", max_length=10)

    with pytest.raises(TypeError):
        validate_key(123)
    with pytest.raises(AirflowException):
        validate_key("a" * 251)
    with pytest.raises(AirflowException):
        validate_key("invalid key")
    with pytest.raises(AirflowException):
        validate_key("invalid..key")


def test_ask_yesno():
    """Test the ask_yesno function with mocked input."""
    with patch("builtins.input", side_effect=["y"]):
        assert ask_yesno("Continue?") is True
    with patch("builtins.input", side_effect=["n"]):
        assert ask_yesno("Continue?") is False
    with patch("builtins.input", side_effect=["", "y"]):
        assert ask_yesno("Continue?", default=True) is True
    with patch("builtins.input", side_effect=["", "n"]):
        assert ask_yesno("Continue?", default=False) is False


def test_prompt_with_timeout():
    """Test the prompt_with_timeout function with mocked input."""
    with patch("builtins.input", side_effect=["y"]):
        assert prompt_with_timeout("Continue?", timeout=1) is True
    with patch("builtins.input", side_effect=["n"]):
        assert prompt_with_timeout("Continue?", timeout=1) is False
    with patch("builtins.input", side_effect=[""]):
        with pytest.raises(AirflowException, match="Timeout 1s reached"):
            prompt_with_timeout("Continue?", timeout=1)


def test_is_container():
    """Test the is_container function with various inputs."""
    assert is_container([1, 2, 3]) is True
    assert is_container("string") is False
    assert is_container(123) is False
    assert is_container(None) is False


def test_chunks():
    """Test the chunks function with various inputs."""
    assert list(chunks([1, 2, 3, 4, 5], 2)) == [[1, 2], [3, 4], [5]]
    assert list(chunks([], 2)) == []
    with pytest.raises(ValueError):
        list(chunks([1, 2, 3], 0))


def test_as_flattened_list():
    """Test the as_flattened_list function with various inputs."""
    assert as_flattened_list([(1, 2), (3, 4)]) == [1, 2, 3, 4]
    assert as_flattened_list([]) == []


def test_parse_template_string():
    """Test the parse_template_string function with various inputs."""
    assert parse_template_string("Hello {{ name }}") == (None, MagicMock())
    assert parse_template_string("Hello World") == ("Hello World", None)


def test_log_filename_template_renderer():
    """Test the log_filename_template_renderer function."""
    renderer = log_filename_template_renderer()
    assert callable(renderer)


def test_convert_camel_to_snake():
    """Test the convert_camel_to_snake function with various inputs."""
    assert convert_camel_to_snake("CamelCase") == "camel_case"
    assert convert_camel_to_snake("HTTPRequest") == "http_request"


def test_merge_dicts():
    """Test the merge_dicts function with two dictionaries."""
    dict1 = {"a": 1, "b": {"c": 2}}
    dict2 = {"b": {"d": 3}, "e": 4}
    expected = {"a": 1, "b": {"c": 2, "d": 3}, "e": 4}
    assert merge_dicts(dict1, dict2) == expected


def test_partition():
    """Test the partition function with a predicate and iterable."""
    def is_even(x):
        return x % 2 == 0

    iterable = [1, 2, 3, 4, 5]
    false_iter, true_iter = partition(is_even, iterable)
    assert list(false_iter) == [1, 3, 5]
    assert list(true_iter) == [2, 4]


def test_build_airflow_dagrun_url():
    """Test the build_airflow_dagrun_url function with mocked base URL."""
    with patch("solution.get_base_url", return_value="http://localhost:8080/"):
        url = build_airflow_dagrun_url("dag_id", "run_id")
        assert url == "http://localhost:8080/dags/dag_id/runs/run_id"


def test_render_template():
    """Test the render_template function with a mocked template."""
    template = MagicMock()
    context = {"key": "value"}
    template.environment = MagicMock()
    template.root_render_func = MagicMock(return_value=["rendered"])
    assert render_template(template, context, native=False) == "rendered"


def test_exactly_one():
    """Test the exactly_one function with various inputs."""
    assert exactly_one(True, False, False) is True
    assert exactly_one(False, False, False) is False
    assert exactly_one(True, True, False) is False
    with pytest.raises(ValueError):
        exactly_one(*[True, False])


def test_at_most_one():
    """Test the at_most_one function with various inputs."""
    assert at_most_one(True, False, False) is True
    assert at_most_one(False, False, False) is True
    assert at_most_one(True, True, False) is False


def test_prune_dict():
    """Test the prune_dict function with various inputs."""
    val = {"a": None, "b": {"c": None, "d": 1}, "e": []}
    expected = {"b": {"d": 1}}
    assert prune_dict(val) == expected
    assert prune_dict(val, mode="truthy") == {"b": {"d": 1}}


def test___getattr__():
    """Test the __getattr__ function with a non-existent attribute."""
    with pytest.raises(AttributeError):
        __getattr__("non_existent")


def test_compute_expression():
    """Test the compute_expression function with various expressions."""
    assert compute_expression("1 + 1") == 2
    assert compute_expression("{'a': 1}") == {'a': 1}
    with pytest.raises(ValueError):
        compute_expression("invalid")